name: Create an issue
author: GiorgioCL
description: "Opens a Github Issue"
inputs:
  token:
    description: "Github Token"
    required: true
  title:
    description: "Issue title"
    required: true
  body:
    description: "Issue boddy"
    required: false
  assignees:
    description: "Issue Assignees"
    required: false
outputs:
  issue:
    description: "The issue object as a json string"
runs:
  using: "node12"
  main: "dist/index.js"
